version: '3'

services:
  database:
    container_name: database
    image: amazon/dynamodb-local
    ports:
    - 8000:8000
    volumes:
    - dynamodb:/home/dynamodblocal

volumes:
    dynamodb:
        driver: local