org: kantahasegawa
app: mizuho-timecard
service: mizuho-timecard

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/Timecards-${opt:stage}
        - arn:aws:dynamodb:${self:provider.region}:*:table/Timecards-${opt:stage}/index/*
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource: arn:aws:s3:::mizuhotimecardsystem-excel-bucket/*

package:
  include:
    - public/**
  exclude:
    - script/**
    - .git/**
    - test/**
    - README.md
    - .env

functions:
  timeCard:
    handler: ./src/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    timecards:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Timecards-${opt:stage}
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: attendance
            AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: attendance
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: usersIndex
            KeySchema:
              - AttributeName: attendance
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: "expirationTime"
          Enabled: true
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mizuhotimecardsystem-excel-bucket

plugins:
  - serverless-plugin-typescript
